version: '3.9'

services:
  backend:
    build: ./backend
    container_name: tictactoe_backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_BACKEND_URL=http://localhost:4000
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always

